# Generated by Django 5.2 on 2025-04-12 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreward',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduledreward',
            name='scheduled_time',
            field=models.DateTimeField(default=None),
        ),
    ]
