
volumes:
  postgres-vol:
    driver: local

networks:
  postgres-net:
    driver: bridge
services:

  db:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - postgres-net
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    entrypoint: |
      bash -c "
        if [ ! -d /var/lib/postgresql/data/pgdata/base ]; then
          /usr/local/bin/docker-entrypoint.sh initdb
          /usr/local/bin/docker-entrypoint.sh postgres
          psql -U postgres -d $POSTGRES_DB -c \"CREATE USER IF NOT EXISTS {POSTGRES_USER} WITH PASSWORD '{POSTGRES_PASSWORD}';\"
        else
          /usr/local/bin/docker-entrypoint.sh postgres
        fi
      "

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      - DOCKER_ENV=1
      - DEBUG=False

    ports:
      - ${APP_PORT}:${APP_PORT}

    depends_on:
      - db
    networks:
      - postgres-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    command: [ "python", "manager.py", "runserver" ]
    restart: unless-stopped
